apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: janet-li-express-sample-app
  app.kubernetes.io/instance: janet-li-express-sample-app-instance
  app.kubernetes.io/name: janet-li-express-sample-app
  app.openshift.io/runtime: js